### PR TITLE
DAOC-32 Make maxOutstandingDisputes variable

### PR DESCRIPTION
**Pull request by italianst4**
Previously the max outstanding disputes were hardcoded to "3". I've updated this by adding a new setter function, for MANAGERS only.  The test suite has been updated to reflect.

### CODE REVIEW

**Comment by ccashwell** [comment]
My only gripe is the naming of `defaultMaxOutstandingDisputes` -- if there's no override setting then it's just the max, not a default. Otherwise this looks good to go.

**Comment by ccashwell** [comment]
By override I mean there's no mapping to set it on a per-feed basis, thus it is a global non-default setting.

**Comment by ccashwell** [comment]
This one is not mergeable as-is due to a conflict.

**Comment by italianst4** [comment]
@ccashwell I've resolved the merge conflicts. Re-compiled and tests are passing. This is ready to be merged in.

**Pull request merged**
